apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryeater
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: memoryeater
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: memoryeater
    spec:
      containers:
      - name: memoryeater
        image: anmalkov/memoryeater:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"