name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore    
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.1
      with:
        context: ./src/
        file: ./src/Dockerfile
        tags: anmalkov/memoryeater
        # Push is a shorthand for --output=type=registry
        #push: # optional, default is false
        # List of output destinations (format: type=local,dest=path)
        # GitHub Token used to authenticate against a repository for Git context
        #github-token: # optional, default is ${{ github.token }}
